### ISSUE TITLE
How to install this plugin?

### ISSUE THREAD

**Issue by ykarthikreddy18** [an-rahulpandey/cordova-plugin-dbcopy#7]
Can you please help me how to install this plugin into my workspace..Im working on android phonegap

**Comment by ykarthikreddy18** [comment]
Hi,
while im trying to run "" cordova plugin add https://github.com/brodysoft/Cordova-SQLitePlugin.git""
It is saying the 
Error: Command failed: C:\Windows\system32\cmd.exe /s /c "git clone "https://git
hub.com/brodysoft/Cordova-SQLitePlugin.git" "C:\Users\karthik\AppData\Local\Temp
\plugman\git\1423631880201""
Cloning into 'C:\Users\karthik\AppData\Local\Temp\plugman\git\1423631880201'...
fatal: The remote end hung up unexpectedly
error: RPC failed; result=7, HTTP code = 0

at ChildProcess.exithandler (child_process.js:744:12)
at ChildProcess.emit (events.js:110:17)
at maybeClose (child_process.js:1008:16)
at Socket.<anonymous> (child_process.js:1176:11)
at Socket.emit (events.js:107:17)
at Pipe.close (net.js:476:12)
..
please help me

I added the git/bin directory path to my system path variables

**Comment by ykarthikreddy18** [comment]
Solution to the above problem i found is, my Appdata folder is Hidden...Make sure that the Appdata folder is unhidden

Thanks rahul for ur response
